version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - amazon-linux-extras install -y maven
  build:
    commands:
      - mvn clean install
      - mvn package
  post_build:
    commands:
      - mkdir -p output
      - cp target/*.war output/
      - cp appspec.yml output/
      - cp *.sh output/

artifacts:
  files:
    - output/**/*
  discard-paths: yes
